# Generated by Django 3.2.6 on 2022-05-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220515_1413'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='firstname',
            field=models.TextField(default='raju', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='lastname',
            field=models.TextField(default='singj', max_length=30),
            preserve_default=False,
        ),
    ]
